name: ci-main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  tf-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform Test
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt install -y terraform
          terraform -version
          ls -ltr
          terraform fmt -diff=true
          terraform init
          terraform validate
  import-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https:// vault-cluster.vault.fb180883-fc88-4186-a68d-22878810dae2.aws.hashicorp.cloud:8200
          token: ${{ secrets.VAULT_TOKEN }}
          namespace: 
          secrets: |
            azure/creds/contributor client_id | ARM_CLIENT_ID ;
            azure/creds/contributor client_secret | ARM_CLIENT_SECRET ;
            secret/data/azure/environment subscription_id | ARM_SUBSCRIPTION_ID;
            secret/data/azure/environment tenant_id | ARM_TENANT_ID ;