name: ci-main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  tf-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import TFC API Token from Vault
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https://vault-cluster.vault.fb180883-fc88-4186-a68d-22878810dae2.aws.hashicorp.cloud:8200
          token: ${{ secrets.VAULT_TOKEN }}
          exportToken: ${{ secrets.VAULT_TOKEN }}
          namespace: admin
          secrets: |
            tfc/creds/ci-team token | TFC_TOKEN ;
      - name: Terraform Test
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt install -y terraform
          terraform -version
          ls -ltr
          terraform fmt -diff=true
          terraform init
          terraform validate
      - name: Import Azure Secrets from Vault
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https://vault-cluster.vault.fb180883-fc88-4186-a68d-22878810dae2.aws.hashicorp.cloud:8200
          token: ${{ secrets.VAULT_TOKEN }}
          exportToken: ${{ secrets.VAULT_TOKEN }}
          namespace: admin
          secrets: |
            azure/creds/contributor client_id | ARM_CLIENT_ID ;
            azure/creds/contributor client_secret | ARM_CLIENT_SECRET ;
            secret/data/azure/environment subscription_id | ARM_SUBSCRIPTION_ID;
            secret/data/azure/environment tenant_id | ARM_TENANT_ID ;
      - name: Set TFC Environmet Variables
        run: |
          cd tf-tfc
          ls -ltr
          terraform init
          export TFE_TOKEN=${TFC_TOKEN}
          export TF_VAR_arm_client_id=${ARM_CLIENT_ID}
          export TF_VAR_arm_client_secret=${ARM_CLIENT_SECRET}
          export TF_VAR_arm_tenant_id=${ARM_TENANT_ID}
          export TF_VAR_arm_sub_id=${ARM_SUBSCRIPTION_ID}
          terraform apply -auto-approve
      - name: Make TFC
        run: |
          cat << EOF > main.tf
          terraform {
            backend "remote" {
              organization = "tkaburagi"

              workspaces {
                name = "azure-vault-gh-actions"
              }
            }
          }

          provider "azurerm" {
              features {}
          }
          EOF

          cat main.tf
      - name: Cleanup Environmet
        run: |
          cd tf-tfc
          ls -ltr
          export TFE_TOKEN=${TFC_TOKEN}
          export TF_VAR_arm_client_id=${ARM_CLIENT_ID}
          export TF_VAR_arm_client_secret=${ARM_CLIENT_SECRET}
          export TF_VAR_arm_tenant_id=${ARM_TENANT_ID}
          export TF_VAR_arm_sub_id=${ARM_SUBSCRIPTION_ID}
          terraform destroy -auto-approve
